services:
  - type: web
    name: tea-project
    env: python
    region: frankfurt
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cd frontend
      npm install
      npm run build
      cd ..
      python manage.py collectstatic --noinput
    startCommand: |
      cp nginx.conf /etc/nginx/conf.d/default.conf
      nginx
      gunicorn backend.tea_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: backend.tea_project.settings
      - key: STATIC_URL
        value: /static/
      - key: DEBUG
        value: "False"
    headers:
      - path: /static/*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /static/*
        name: Access-Control-Allow-Methods
        value: "GET, OPTIONS"
      - path: /static/*
        name: Access-Control-Allow-Headers
        value: "*"
      - path: /static/*.css
        name: Content-Type
        value: text/css
      - path: /static/*
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /assets/*
        name: Access-Control-Allow-Methods
        value: "GET, OPTIONS"
      - path: /assets/*
        name: Access-Control-Allow-Headers
        value: "*"
      - path: /assets/*
        name: Cache-Control
        value: no-cache
    autoDeploy: false
    pythonVersion: 3.11.8
    staticPublishPath: ./staticfiles
    staticUrlPrefix: /static 