services:
  - type: web
    name: tea-project
    env: python
    region: frankfurt
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: false
    pythonVersion: 3.11.8
    staticPublishPath: ./staticfiles
    staticBuildCommand: python manage.py collectstatic --noinput 